### ISSUE TITLE
Compilation issue on Ubuntu 14.04

### ISSUE THREAD

**Issue by aragua** [haka-security/haka#3]
Haka develop branch can't compile on Ubuntu14.04 due to python error.
I have to comment documentation in CMakeLists.txt in order to complete compilation.

This is error output :
" ...
Scanning dependencies of target doc
[  5%] Generating user guide
Making output directory...
Running Sphinx v1.2.2
loading pickled environment... not yet created
building [html]: targets for 48 source files that are out of date
updating environment: 48 added, 0 changed, 0 removed
reading sources... [100%] modules/protocol/udp/doc/lua  
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  6%] doc/developer/c/log_alert  
Exception occurred:
  File "/usr/lib/python2.7/dist-packages/sphinx/writers/html.py", line 155, in visit_desc_parameter
    self.required_params_left -= 1
AttributeError: SmartyPantsHTMLTranslator instance has no attribute 'required_params_left'
The full traceback has been saved in /tmp/sphinx-err-NP_zMf.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://bitbucket.org/birkenfeld/sphinx/issues/. Thanks!
make[2]: **\* [doc/CMakeFiles/doc] Erreur 1
make[1]: **\* [doc/CMakeFiles/doc.dir/all] Erreur 2
make: **\* [all] Erreur 2
"
